# 订阅源配置
# 生产环境应将此文件放入 RESOURCES_DIR 目录

sources:
  - tag: "订阅A"
    from: "https://v2.fastlink-aff02.com/user"
    url: "https://10ncydlf.flsubcn.cc:2096/zvlqjih1t/03sbkrfeccbopfzf?clash=1&extend=1"
    protocol: "clash"
    enabled: true
    prefix: "Master" # 节点名称前缀（可选，默认使用tag）
    cacheEnabled: true # 启用缓存（可选，默认false）
    cacheTtlDays: 999 # 缓存天数（可选，默认30天）
